In [47]:
import numpy as np

from itertools import product

In [ ]:
# def m_generator(j, disallowed=set()):
#     m = j

#     while m in disallowed:
#         m -= 1

#     while m >= 0:
#         yield m
#         m -= 1
#         while m in disallowed:
#             m -= 1

In [111]:
def m_generator(j, allow_neg=True):
    m = j

    last = -j if allow_neg else 0
    
    while m >= last:
        yield m
        m -= 1

In [68]:
def is_fermion(j):
    return j != int(j)

In [ ]:
def total_m_generator(particle_js, allow_neg=False):

    are_fermions = np.array([is_fermion(j) for j in particle_js])

    m_generators = [m_generator(particle_js[0], allow_neg=False)] + [m_generator(j) for j in particle_js[1:]]

    for ms in product(*m_generators):
        ms = np.array(ms)

        # ordering
        if np.any(np.diff(ms) > 0):
            continue
        
        # Pauli exclusion
        fermion_ms = ms[are_fermions]
        if fermion_ms.size != np.unique(fermion_ms).size:
            continue
        
        # negative m
        if not allow_neg and np.sum(ms) < 0:
            continue

        yield ms, np.sum(ms)
        

In [207]:
def allowed_total_j(particle_js):
    m_tots = [m_tots for ms, m_tots in total_m_generator(particle_js)]
    allowed_total_j = []

    while m_tots:
        # print(m_tots)
        biggest_m_tot = m_tots.pop(0)
        allowed_total_j.append(biggest_m_tot)

        for j in m_generator(biggest_m_tot-1, allow_neg=False):
            m_tots.remove(np.float64(j))

    return np.array(allowed_total_j)

In [208]:
for ms, m_tots in total_m_generator([5/2, 5/2, 5/2]):
    print(ms, m_tots)
allowed_total_j([5/2, 5/2, 5/2])

[2.5 1.5 0.5] 4.5
[ 2.5  1.5 -0.5] 3.5
[ 2.5  1.5 -1.5] 2.5
[ 2.5  1.5 -2.5] 1.5
[ 2.5  0.5 -0.5] 2.5
[ 2.5  0.5 -1.5] 1.5
[ 2.5  0.5 -2.5] 0.5
[ 2.5 -0.5 -1.5] 0.5
[ 1.5  0.5 -0.5] 1.5
[ 1.5  0.5 -1.5] 0.5


array([4.5, 2.5, 1.5])

In [209]:
for ms, m_tots in total_m_generator([2,2,2]):
    print(ms, m_tots)
allowed_total_j([2,2,2])

[2 2 2] 6
[2 2 1] 5
[2 2 0] 4
[ 2  2 -1] 3
[ 2  2 -2] 2
[2 1 1] 4
[2 1 0] 3
[ 2  1 -1] 2
[ 2  1 -2] 1
[2 0 0] 2
[ 2  0 -1] 1
[ 2  0 -2] 0
[ 2 -1 -1] 0
[1 1 1] 3
[1 1 0] 2
[ 1  1 -1] 1
[ 1  1 -2] 0
[1 0 0] 1
[ 1  0 -1] 0
[0 0 0] 0


array([6, 4, 2, 3, 0])

In [210]:
print("Allowed J for n quadrupole phonons:")
print("n", "J")
for i in range(1, 9):
    print(i, allowed_total_j([2]*i))

Allowed J for n quadrupole phonons:
n J
1 [2]
2 [4 2 0]
3 [6 4 2 3 0]
4 [8 6 4 5 2 4 2 0]
5 [10  8  6  7  4  6  4  2  5  3  2  0]
6 [12 10  8  9  6  8  6  4  7  5  4  2  6  4  3  2  0  0]
7 [14 12 10 11  8 10  8  6  9  7  6  4  8  6  5  4  2  2  7  5  4  3  2  0]
8 [16 14 12 13 10 12 10  8 11  9  8  6 10  8  7  6  4  4  9  7  6  5  4  2
  8  6  5  4  2  3  2  0  0]


In [228]:
total_ms = []
for i,j in total_m_generator([2]*6): 
    total_ms.append(j)
    # print(i,j)

print()
print(np.array(total_ms))
unique_vals, counts = np.unique(total_ms, return_counts=True)

print()

unique_vals = unique_vals[::-1]
counts = counts[::-1]

print(unique_vals)
print(counts)


[12 11 10  9  8 10  9  8  7  8  7  6  6  5  4  9  8  7  6  7  6  5  5  4
  3  6  5  4  4  3  2  3  2  1  0  8  7  6  5  6  5  4  4  3  2  5  4  3
  3  2  1  2  1  0  4  3  2  2  1  0  1  0  0  7  6  5  4  5  4  3  3  2
  1  4  3  2  2  1  0  1  0  3  2  1  1  0  0  2  1  0  0  6  5  4  3  4
  3  2  2  1  0  3  2  1  1  0  0  2  1  0  0  1  0  0]

[12 11 10  9  8  7  6  5  4  3  2  1  0]
[ 1  1  2  3  5  6  9 10 13 14 16 16 18]


[np.int64(12), np.int64(11), np.int64(10), np.int64(9), np.int64(8), np.int64(10), np.int64(9), np.int64(8), np.int64(7), np.int64(8), np.int64(7), np.int64(6), np.int64(6), np.int64(5), np.int64(4), np.int64(9), np.int64(8), np.int64(7), np.int64(6), np.int64(7), np.int64(6), np.int64(5), np.int64(5), np.int64(4), np.int64(3), np.int64(6), np.int64(5), np.int64(4), np.int64(4), np.int64(3), np.int64(2), np.int64(3), np.int64(2), np.int64(1), np.int64(0), np.int64(8), np.int64(7), np.int64(6), np.int64(5), np.int64(6), np.int64(5), np.int64(4), np.int64(4), np.int64(3), np.int64(2), np.int64(5), np.int64(4), np.int64(3), np.int64(3), np.int64(2), np.int64(1), np.int64(2), np.int64(1), np.int64(0), np.int64(4), np.int64(3), np.int64(2), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(7), np.int64(6), np.int64(5), np.int64(4), np.int64(5), np.int64(4), np.int64(3), np.int64(3), np.int64(2), np.int64(1), np.int64(4), np.int64(3), np.int64(2), np.int6

array([12, 10,  8,  9,  6,  8,  6,  4,  7,  5,  4,  2,  6,  4,  3,  2,  0,
        0])